################################################################################
# Copyright (c) 2022, 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# Copyright (c) 2022, 2023 ZF Friedrichshafen AG
# Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

spring:
  flyway:
    locations: /db/migration,/db/testdata-hella,${flyway.truncate-location}
    placeholders:
      bpnOwn:       "'BPNL000000000001'"
      bpnSupplier1: "'BPNL000SUPPLIER1'"
      bpnSupplier2: "'BPNL000SUPPLIER2'"
      bpnSupplier3: "'BPNL000SUPPLIER3'"
      bpnCustomer1: "'BPNL00000000GNDU'"
      bpnCustomer2: "'BPNL000CUSTOMER2'"
      bpnCustomer3: "'BPNL000CUSTOMER3'"

      assetAsBuiltId01: "'urn:uuid:6ec3f1db-2798-454b-a73f-0d21a8966c77'"
      assetAsBuiltId02: "'urn:uuid:132fd82b-caab-476b-b453-b7273a4c7c01'"
      assetAsBuiltId03: "'urn:uuid:c0edce5c-546f-4e79-9d86-a4cb7ca7b900'"
      assetAsBuiltId04: "'urn:uuid:6b739098-dec0-4726-b5cb-e8cd5091a9f2'"
      assetAsBuiltId05: "'urn:uuid:0f440d8a-4c74-417b-b217-bbcd1aebdd8d'"
      assetAsBuiltId06: "'urn:uuid:b3707747-59f2-46f3-98c7-a5a77fdb2d2f'"
      assetAsBuiltId07: "'urn:uuid:c032bf1f-38a6-4a73-b64c-02ce0853dc42'"
      assetAsBuiltId08: "'urn:uuid:6d547770-01f5-4618-b055-4f0b86e2924f'"
      assetAsBuiltId09: "'urn:uuid:c09aa1f9-c8f4-4e92-935a-ea64ac703e33'"
      assetAsBuiltId10: "'urn:uuid:135249bf-2a52-499f-a686-1377ecc38ab7'"
      assetAsBuiltId11: "'urn:uuid:2bb95b83-4136-4d1b-a97b-ecbc2814369e'"
      assetAsBuiltId12: "'urn:uuid:cfbc8379-eaa1-4374-b472-09c0c9b50a0a'"
      assetAsBuiltId13: "'urn:uuid:6e082245-7171-4593-8038-d3b15c27b5f9'"
      assetAsBuiltId14: "'urn:uuid:059bd389-e7fb-4127-991f-d8b36353975c'"
      assetAsBuiltId15: "'urn:uuid:0f643092-1c2e-453e-8cf1-4069fd055111'"
      assetAsBuiltId16: "'urn:uuid:998ab013-0cdc-41b2-9abc-8e6e5d6ba974'"
      assetAsBuiltId17: "'urn:uuid:907d3ec4-f91c-434d-b46a-34fb0250e05b'"
      assetAsBuiltId18: "'urn:uuid:1e04733b-741e-4bed-a4b5-9c4b0fa0860c'"
      assetAsBuiltId19: "'urn:uuid:91a8d11a-e5f6-40e8-a187-8b9f7eecdc57'"
      assetAsBuiltId20: "'urn:uuid:614bdfcf-6e86-43f5-a295-f791a92859f1'"
      assetAsBuiltId21: "'urn:uuid:9e85f88a-2e6b-40fe-a7b2-1a0c64ea0ad4'"
      assetAsBuiltId22: "'urn:uuid:b69cb0d1-0cbe-4f47-ac34-a4b7ef5cd6ff'"
      assetAsBuiltId23: "'urn:uuid:3d0e7c0d-6aa1-43f7-8fe5-88d7e71da4f7'"
      assetAsBuiltId24: "'urn:uuid:dbffab7f-4fcd-4d09-bd35-fedd5dd2f141'"
      assetAsBuiltId25: "'urn:uuid:11b5fa3a-f5ab-471b-885b-70949a41c179'"
      assetAsBuiltId26: "'urn:uuid:db5ea31d-cbd7-45ff-b079-2a8ad2093a92'"
      assetAsBuiltId27: "'urn:uuid:6bebac2c-ef0e-4a8d-a9f3-ad144af875a9'"
      assetAsBuiltId28: "'urn:uuid:524918bd-8550-47cb-9a72-2c52765df25e'"
      assetAsBuiltId29: "'urn:uuid:e0a485de-c989-4afa-966f-f3d5553bdbcb'"
      assetAsBuiltId30: "'urn:uuid:828c01ba-3a03-43b6-b71b-b86a4a2d9549'"

      assetAsPlannedId01: "'urn:uuid:e97699c1-89c1-474b-8a92-c3a887c6b4c0'"
      assetAsPlannedId02: "'urn:uuid:78e5523d-73b6-4770-b5f5-5ea314c33674'"
      assetAsPlannedId03: "'urn:uuid:233fda23-3d10-454e-abec-6cb29813bcd5'"
      assetAsPlannedId04: "'urn:uuid:cce342a3-910f-4802-b8a2-c37c59344cf2'"
      assetAsPlannedId05: "'urn:uuid:daa579ab-23e5-407b-b2cf-0b24ff400fec'"
      assetAsPlannedId06: "'urn:uuid:25f34391-f73c-49f7-bcf5-95c1c8de4f2e'"
      assetAsPlannedId07: "'urn:uuid:94be6a68-f8f0-47e2-9a23-a37d15c0c680'"
      assetAsPlannedId08: "'urn:uuid:2af628f6-522f-4eb9-aeff-2e52ed619548'"
      assetAsPlannedId09: "'urn:uuid:e266a50e-174d-4e73-9158-3a98eac1ad58'"
      assetAsPlannedId10: "'urn:uuid:c8d6ebd6-f205-430f-93d1-d09a1540d307'"
      assetAsPlannedId11: "'urn:uuid:d1421674-bef8-4cfe-996e-8a261979647a'"
      assetAsPlannedId12: "'urn:uuid:2a107d93-8401-4684-ac51-449026ee8242'"
      assetAsPlannedId13: "'urn:uuid:d77e93ea-a4ea-4749-90e2-53233628427d'"
      assetAsPlannedId14: "'urn:uuid:f40306d8-b968-48a7-908e-dbcc52548047'"
      assetAsPlannedId15: "'urn:uuid:44120129-a42c-4178-9ce0-0ad0c92dba6e'"
      assetAsPlannedId16: "'urn:uuid:986fbb89-3074-4508-af6b-c563dfc5b89f'"
      assetAsPlannedId17: "'urn:uuid:c658a87e-320a-4986-bee0-49b5651a6d2c'"
      assetAsPlannedId18: "'urn:uuid:4a7601b3-38ff-40e6-91c5-cfcc993fc7bf'"
      assetAsPlannedId19: "'urn:uuid:6b3aac2d-1c90-4f40-abec-9171009c8d59'"
      assetAsPlannedId20: "'urn:uuid:058ee79f-1996-4d85-9ac9-2e9bcca9e744'"
      assetAsPlannedId21: "'urn:uuid:2e4bd1cb-5017-44ca-b1af-eb72f901d772'"
      assetAsPlannedId22: "'urn:uuid:8f34a5c5-97a8-4a3a-ad41-71797a815daa'"
      assetAsPlannedId23: "'urn:uuid:49aa542f-49a8-42ef-ba6a-6dbc3ba17e9f'"
      assetAsPlannedId24: "'urn:uuid:48654605-b474-4117-98df-2731e215ea9d'"
      assetAsPlannedId25: "'urn:uuid:0af36a03-73a5-4cda-9c4f-9e2fdc4b83b6'"
      assetAsPlannedId26: "'urn:uuid:ebfae9ab-8d7d-49d4-a235-194ca25e3996'"
      assetAsPlannedId27: "'urn:uuid:dff741cd-111a-4c46-a3a0-162516258f69'"
      assetAsPlannedId28: "'urn:uuid:84a2c8ac-b05d-447f-8879-3ab1f9ade76c'"
      assetAsPlannedId29: "'urn:uuid:6fe70423-5e1d-4b2f-b946-3d526f6a869b'"
      assetAsPlannedId30: "'urn:uuid:26032839-8ca6-43d5-81c7-f51868321119'"

      alertSentId1: 1
      alertSentId2: 2
      alertSentId3: 3
      alertSentId4: 4
      alertSentId5: 5
      alertSentId6: 6
      alertSentId7: 7

      alertReceivedId1: 11
      alertReceivedId2: 12
      alertReceivedId3: 13
      alertReceivedId4: 14
      alertReceivedId5: 15

      alertNotificationSentId1: "'4939c189-b75d-4647-94cb-a75b83a92313'"
      alertNotificationSentId2: "'a15583ac-101e-44e0-9fba-33ceaa4d3540'"
      alertNotificationSentId3a: "'8b1319a4-4ba8-46bc-a0b0-1c71d9186d25'"
      alertNotificationSentId3b: "'cab39b22-3938-4b27-9a78-68ef980147dc'"
      alertNotificationSentId4a: "'86ef99d6-15c9-4bb0-87ee-9828fe06a3d2'"
      alertNotificationSentId4b: "'c8216fd5-88cf-44eb-baa5-c942912cae7e'"
      alertNotificationSentId5a: "'3d5a6398-c807-4bb8-9a8c-7bc436988964'"
      alertNotificationSentId5b: "'35b7e479-7469-4b83-bfc1-0f0c13ad09f6'"
      alertNotificationSentId6: "'0b2ee6b3-6bc8-487d-b8f2-75c027e51b26'"
      alertNotificationSentId7a: "'21bc7f55-59ae-4711-b961-6af1a7c25757'"
      alertNotificationSentId7b: "'f03a4de5-0820-45bb-828e-96e38d433c87'"

      alertNotificationReceivedId1: "'e3de866d-044b-4db9-9349-841365189a9b'"
      alertNotificationReceivedId2a: "'98d5107c-f11b-4a69-9207-906c660be7f6'"
      alertNotificationReceivedId2b: "'194b32b5-8b28-40d8-a29a-58a30a1ac2c5'"
      alertNotificationReceivedId3a: "'df5b7e53-5b5e-445b-adbe-0fe6dabc05e3'"
      alertNotificationReceivedId3b: "'d51d8ea4-67b1-49ed-a0c0-b40a452362db'"
      alertNotificationReceivedId4a: "'fef2174d-4ea6-4b06-b189-6f7fe7809418'"
      alertNotificationReceivedId4b: "'cf6e4290-6d86-4a8e-94f1-8fee275ce133'"
      alertNotificationReceivedId5a: "'38c47db2-9f92-4e58-9d5b-3245c064d0fa'"
      alertNotificationReceivedId5b: "'317fa3d4-126a-424d-a030-aa53384573fd'"

      investigationSentId1: 1
      investigationSentId2: 2
      investigationSentId3: 3
      investigationSentId4: 4
      investigationSentId5: 5
      investigationSentId6: 6
      investigationSentId7: 7

      investigationReceivedId1: 11
      investigationReceivedId2: 12
      investigationReceivedId3: 13
      investigationReceivedId4: 14
      investigationReceivedId5: 15

      investigationNotificationSentId1: "'7486286d-a098-4617-81ea-3015bc866a7e'"
      investigationNotificationSentId2: "'94032934-8ec8-4f97-a38d-6b16d448cbfb'"
      investigationNotificationSentId3a: "'b5b4612e-6ed6-47c2-8f52-adefe3d5b99a'"
      investigationNotificationSentId3b: "'62eea0b3-c8b1-48d9-a220-cb01c3a3f4fe'"
      investigationNotificationSentId4a: "'36e270c0-4a40-4516-b2f0-c21f8c033f2b'"
      investigationNotificationSentId4b: "'317fa3d4-126a-424d-a030-aa53384573fd'"
      investigationNotificationSentId5a: "'531ca5d8-3634-4439-8090-743a7a63be75'"
      investigationNotificationSentId5b: "'a5444374-a0a6-452a-9d45-079930468800'"
      investigationNotificationSentId6: "'54511ec0-304b-41ef-8426-6585a1ee1558'"
      investigationNotificationSentId7a: "'6adc3d93-7efb-4c2b-bd9d-bbb1b61549f0'"
      investigationNotificationSentId7b: "'8e866bf4-fa92-43fb-a012-a27556659579'"

      investigationNotificationReceivedId1: "'0678b9c6-a9c4-4ff9-a5e2-c6cd19c5f8c6'"
      investigationNotificationReceivedId2a: "'3fbd0206-2507-445c-aa6b-ec726d0eeae2'"
      investigationNotificationReceivedId2b: "'989ae19d-d682-4c1b-baaf-4bb779d91d8d'"
      investigationNotificationReceivedId3a: "'7561d71a-0706-4dd9-bf7e-29d8be482e19'"
      investigationNotificationReceivedId3b: "'2dae86e5-77b6-449c-b51d-6031e39f0fcb'"
      investigationNotificationReceivedId4a: "'907e4a54-7855-454b-a8e7-5be3d46496c9'"
      investigationNotificationReceivedId4b: "'829f95f4-38a8-4678-b761-ff66346a047e'"
      investigationNotificationReceivedId5a: "'55781066-d7ae-41f2-8adb-133983f18c2a'"
      investigationNotificationReceivedId5b: "'a9c8fa69-5e6b-4adc-99a2-307bf3a83f5d'"
