################################################################################
# Copyright (c) 2022, 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# Copyright (c) 2022, 2023 ZF Friedrichshafen AG
# Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

spring:
  flyway:
    locations: /db/migration,/db/testdata-trial
    placeholders:

      bpnOwn           : "'BPNL000000000001'"
      bpnOwnName       : "'SupOne'"

      bpnSupplier1    : "'BPNL000SUPPLIER1'"
      bpnSupplier1Name: "'LuminaTech'"
      bpnSupplier2    : "'BPNL000SUPPLIER2'"
      bpnSupplier2Name: "'BrightSolutions'"
      bpnSupplier3    : "'BPNL000SUPPLIER3'"
      bpnSupplier3Name: "'CableCraft'"

      bpnSupplier4    : "'BPNL000SUPPLIER4'"
      bpnSupplier4Name: "'Linkage'"
      bpnSupplier5    : "'BPNL000SUPPLIER5'"
      bpnSupplier5Name: "'LuxLite'"
      bpnSupplier6    : "'BPNL000SUPPLIER6'"
      bpnSupplier6Name: "'CaseFactory'"

      bpnCustomer1    : "'BPNL00000000GNDU'"
      bpnCustomer1Name: "'Manu'"
      bpnCustomer2    : "'BPNL000CUSTOMER2'"
      bpnCustomer2Name: "'Mecury'"

      assetAsBuiltId01: "'urn:uuid:0d21a896-a73f-454b-2798-6c776ec3f1db'"
      assetAsBuiltId02: "'urn:uuid:b7273a4c-b453-476b-caab-7c01132fd82b'"
      assetAsBuiltId03: "'urn:uuid:a4cb7ca7-9d86-4e79-546f-b900c0edce5c'"
      assetAsBuiltId04: "'urn:uuid:e8cd5091-b5cb-4726-dec0-a9f26b739098'"
      assetAsBuiltId05: "'urn:uuid:bbcd1aeb-b217-417b-4c74-dd8d0f440d8a'"
      assetAsBuiltId06: "'urn:uuid:a5a77fdb-98c7-46f3-59f2-2d2fb3707747'"
      assetAsBuiltId07: "'urn:uuid:02ce0853-b64c-4a73-38a6-dc42c032bf1f'"
      assetAsBuiltId08: "'urn:uuid:4f0b86e2-b055-4618-01f5-924f6d547770'"
      assetAsBuiltId09: "'urn:uuid:ea64ac70-935a-4e92-c8f4-3e33c09aa1f9'"
      assetAsBuiltId10: "'urn:uuid:1377ecc3-a686-499f-2a52-8ab7135249bf'"
      assetAsBuiltId11: "'urn:uuid:ecbc2814-a97b-4d1b-4136-369e2bb95b83'"
      assetAsBuiltId12: "'urn:uuid:09c0c9b5-b472-4374-eaa1-0a0acfbc8379'"
      assetAsBuiltId13: "'urn:uuid:d3b15c27-8038-4593-7171-b5f96e082245'"
      assetAsBuiltId14: "'urn:uuid:d8b36353-991f-4127-e7fb-975c059bd389'"
      assetAsBuiltId15: "'urn:uuid:4069fd05-8cf1-453e-1c2e-51110f643092'"
      assetAsBuiltId16: "'urn:uuid:8e6e5d6b-9abc-41b2-0cdc-a974998ab013'"
      assetAsBuiltId17: "'urn:uuid:34fb0250-b46a-434d-f91c-e05b907d3ec4'"
      assetAsBuiltId18: "'urn:uuid:9c4b0fa0-a4b5-4bed-741e-860c1e04733b'"
      assetAsBuiltId19: "'urn:uuid:8b9f7eec-a187-40e8-e5f6-dc5791a8d11a'"
      assetAsBuiltId20: "'urn:uuid:f791a928-a295-43f5-6e86-59f1614bdfcf'"
      assetAsBuiltId21: "'urn:uuid:1a0c64ea-a7b2-40fe-2e6b-0ad49e85f88a'"
      assetAsBuiltId22: "'urn:uuid:a4b7ef5c-ac34-4f47-0cbe-d6ffb69cb0d1'"

traceability:
  bpn: {bpnOwn}
