name: "[BE][FE] Release"

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calculate Helm release version from CHANGELOG
        run: echo HELM_VERSION=$(cat charts/traceability-foss/CHANGELOG.md | sed -n 's/.*\[\([0-9]\+\.[0-9]\+\.[0-9]\+\)\].*/\1/p' | head -n 1) >> $GITHUB_ENV

      - name: Update Chart.yaml appVersion
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i eval '.appVersion = "${{ github.ref_name }}"' charts/traceability-foss/Chart.yaml

      - name: Update Chart.yaml version
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i eval '.version = "${{ env.HELM_VERSION }}"' charts/traceability-foss/Chart.yaml

      - name: Update frontend dependency version in Chart.yaml
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i eval '.dependencies[0].version = "${{ env.HELM_VERSION }}"' charts/traceability-foss/Chart.yaml

      - name: Update backend dependency version in Chart.yaml
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i eval '.dependencies[1].version = "${{ env.HELM_VERSION }}"' charts/traceability-foss/Chart.yaml

      - name: Update frontend version in frontend/Chart.yaml
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i eval '.version = "${{ env.HELM_VERSION }}"' charts/traceability-foss/charts/frontend/Chart.yaml

      - name: Update frontend appVersion in frontend/Chart.yaml
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i eval '.appVersion = "${{ github.ref_name }}"' charts/traceability-foss/charts/frontend/Chart.yaml

      - name: Update backend version in backend/Chart.yaml
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i eval '.version = "${{ env.HELM_VERSION }}"' charts/traceability-foss/charts/backend/Chart.yaml

      - name: Update backend appVersion in frontend/Chart.yaml
        uses: mikefarah/yq@v4.35.2
        with:
          cmd: yq -i eval '.appVersion = "${{ github.ref_name }}"' charts/traceability-foss/charts/backend/Chart.yaml

      - name: Update the frontend package.json appVersion
        run: |
          npm install -g json
          json -I -f frontend/package.json -e "this.version='${{ github.ref_name }}'"

      - name: Prepare patch
        run: |
          git diff --cached > helm-release.patch

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: helm-release.patch
          path: helm-release.patch

      - name: Get previous version
        run: echo PREVIOUS_VERSION=$(git tag | grep -E ^[0-9]+\\.[0-9]+\\.[0-9]+ | tail -2 | head -n +1) >> $GITHUB_ENV

      - name: Extract changelog text
        # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "CHANGELOG<<$EOF" >> $GITHUB_ENV
          sed -n -e '/## \[${{ github.ref_name }}\]/,/## \[/ p' CHANGELOG.md | head -n -1 | tail -n +2 >> $GITHUB_ENV
          echo **Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/${{ env.PREVIOUS_VERSION }}...${{ github.ref_name }} >> $GITHUB_ENV
          echo "$EOF" >> "$GITHUB_ENV"

      - name: Create Trace-X Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ env.CHANGELOG }}
